### ISSUE TITLE
maplibre build-dev "TypeError: defaultLoader is not a function"

### ISSUE THREAD

**Issue by SPBNike** [maplibre/maplibre-gl-js#1133]
### Discussed in https://github.com/maplibre/maplibre-gl-js/discussions/1132

<div type='discussions-op-text'>

<sup>Originally posted by **SPBNike** March 30, 2022</sup>
Getting the error below trying to build maplibre on my Windows box. Followed the CONTRIBUTING.md steps (node, windows-dev-tools, npm i, ...) and I'm currently stuck on this error.

I've paved clean the repo, reinstalled node / windows-dev-tools, ... but it still occurs.

```
d:\gdev\maplibre-gl-js>npm run build-dev

> maplibre-gl@2.1.7 build-dev
> rollup --configPlugin @rollup/plugin-typescript -c --environment BUILD:dev --verbose

[!] TypeError: defaultLoader is not a function
TypeError: defaultLoader is not a function
    at Object.require.extensions.<computed> [as .ts] (d:\gdev\maplibre-gl-js\node_modules\rollup\dist\shared\loadConfigFile.js:617:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (d:\gdev\maplibre-gl-js\node_modules\rollup\dist\shared\loadConfigFile.js:622:42)
    at loadConfigFile (d:\gdev\maplibre-gl-js\node_modules\rollup\dist\shared\loadConfigFile.js:565:11)
    at Object.loadAndParseConfigFile (d:\gdev\maplibre-gl-js\node_modules\rollup\dist\shared\loadConfigFile.js:545:21)
    at getConfigs (d:\gdev\maplibre-gl-js\node_modules\rollup\dist\bin\rollup:1691:39)
    at runRollup (d:\gdev\maplibre-gl-js\node_modules\rollup\dist\bin\rollup:1665:43)</div>

**Comment by HarelM** [comment]
This is probably related to node version etc.
Build is passing in general.
Closing...
Let us know if you face more issues...
Sorry for the late respond...
