### ISSUE TITLE
Layout benchmark broken

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1254]
The Layout benchmark seems to be broken. Thanks @ambientlight for pointing this out.

Steps to reproduce the problem:
```
npm ci
npm run generate-typings && npm run build-prod && npm run build-csp && npm run build-dev && npm run build-css && npm run build-style-spec

npm run start-bench
```
(maybe I should put all the build commands in a build-all?)

Then open your browser, got to http://localhost:9966/bench/versions and wait for the Layout benchmark to show up (~~side note, one should be able to open http://localhost:9966/bench/versions?compare=main#Layout to see only the layout benchmark, but this is broken, too~~ works on a clean install).  Open the browser console and you will find the following error message

```
style.ts:503 Uncaught TypeError: Cannot read properties of undefined (reading 'updateElevation')
    at oe.setTerrain (style.ts:503:32)
    at oe._load (style.ts:287:14)
    at style.ts:242:18
```

Going forward, we should really refactor the benchmarks and run them in CI. This would maybe not give significant numbers, but at least we could see if the benchmarks still work.

**Comment by wipfli** [comment]
The above error message is from chrome. Firefox says:
```
Uncaught TypeError: this.map.transform is undefined
    setTerrain style.ts:503
    _load style.ts:287
    _request style.ts:242
```

**Comment by wipfli** [comment]
#1238 mentions that the following benchmarks are bad: Layout, WorkerTransfer, SymbolLayout, HillshadeLoad

**Comment by wipfli** [comment]
HilshadeLoad works for me. The others (Layout, WorkerTransfer, SymbolLayout) all show the same console error:

```
style.ts:505 Uncaught TypeError: Cannot read properties of undefined (reading 'updateElevation')
    at oe.setTerrain (style.ts:505:32)
    at oe._load (style.ts:287:14)
    at style.ts:242:18
```

**Comment by wipfli** [comment]
They are the only three benchmarks which use `this.parser.parseTile()` inside the setup function.
