### ISSUE TITLE
Unable to run query and browser tests on Windows

### ISSUE THREAD

**Issue by kircher1** [maplibre/maplibre-gl-js#1501]
I'm using a recent version of main (b9458a48655acc00f48d21eca2553b18a7b100ce), Node 16.4.0, and VS code.

Test execution fails (`npm run test-query` or `num run test-browser`) and results in the following error and stack:

```
Failure message: MurmurHash3 is not a function
    at getTmpname (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\node_modules\write-file-atomic\lib\index.js:31:5)
    at writeFileSync (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\node_modules\write-file-atomic\lib\index.js:184:19)
    at writeCacheFile (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:1014:33)
    at writeCodeCacheFile (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:977:3)
    at ScriptTransformer._buildTransformResult (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:582:5)
    at ScriptTransformer.transformSource (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:628:17)
    at revertHook.exts (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:871:18)
    at Module._compile (C:\GitHub\maplibre-gl-js\node_modules\pirates\lib\index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at require.extensions.<computed> (C:\GitHub\maplibre-gl-js\node_modules\ts-node\src\index.ts:1608:43)
```

**Comment by HarelM** [comment]
Can you add a CI step for Windows maybe so we can see the error as part of a PRs CI run?

**Comment by kircher1** [comment]
Update: Running `npx jest --clearCache` before running the test circumvents the above error.

**Comment by HarelM** [comment]
This was fixed, wasn't it? Closing... let me know if there's a need to reopen this.

**Comment by kircher1** [comment]
Not fixed but clearing the jest cache is a simple workaround. (`npx jest --clearCache`)
