### ISSUE TITLE
Jest cache error - MurmurHash3 is not a function

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#1504]
When running i.e. `npm run test-browser` or `npm run test-query`, often an issue occurs that will only be resolved when running `jest --clearCache` between every run.

### on windows

https://github.com/maplibre/maplibre-gl-js/issues/1501

```
Failure message: MurmurHash3 is not a function
    at getTmpname (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\node_modules\write-file-atomic\lib\index.js:31:5)
    at writeFileSync (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\node_modules\write-file-atomic\lib\index.js:184:19)
    at writeCacheFile (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:1014:33)
    at writeCodeCacheFile (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:977:3)
    at ScriptTransformer._buildTransformResult (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:582:5)
    at ScriptTransformer.transformSource (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:628:17)
    at revertHook.exts (C:\GitHub\maplibre-gl-js\node_modules\@jest\transform\build\ScriptTransformer.js:871:18)
    at Module._compile (C:\GitHub\maplibre-gl-js\node_modules\pirates\lib\index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at require.extensions.<computed> (C:\GitHub\maplibre-gl-js\node_modules\ts-node\src\index.ts:1608:43)
```

### on mac

```
> jest -c ./jest.config.e2e.ts --roots ./test/integration/browser

TypeError: jest: failed to cache transform results in: /private/var/folders/cj/hw95k0jd3gn2q4j659rptp3r0000gn/T/jest_dx/jest-transform-cache-92154bf7d0b758a0d632083a424cf7bc-2697e17f6738341b1cdada512ba46f39/bb/imurmurhash_bb34805d145ad02ceee6fd044c411045
Failure message: MurmurHash3 is not a function
    at getTmpname (/Users/admin/repos/maplibre-gl-js/node_modules/@jest/transform/node_modules/write-file-atomic/lib/index.js:31:5)
    at writeFileSync (/Users/admin/repos/maplibre-gl-js/node_modules/@jest/transform/node_modules/write-file-atomic/lib/index.js:184:19)
    at writeCacheFile (/Users/admin/repos/maplibre-gl-js/node_modules/@jest/transform/build/ScriptTransformer.js:1014:33)
    at writeCodeCacheFile (/Users/admin/repos/maplibre-gl-js/node_modules/@jest/transform/build/ScriptTransformer.js:977:3)
    at ScriptTransformer._buildTransformResult (/Users/admin/repos/maplibre-gl-js/node_modules/@jest/transform/build/ScriptTransformer.js:582:5)
    at ScriptTransformer.transformSource (/Users/admin/repos/maplibre-gl-js/node_modules/@jest/transform/build/ScriptTransformer.js:628:17)
    at revertHook.exts (/Users/admin/repos/maplibre-gl-js/node_modules/@jest/transform/build/ScriptTransformer.js:871:18)
    at Module._compile (/Users/admin/repos/maplibre-gl-js/node_modules/pirates/lib/index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at require.extensions.<computed> (/Users/admin/repos/maplibre-gl-js/node_modules/ts-node/src/index.ts:1608:43)
```

**Comment by HarelM** [comment]
@birkskyum what would you like to do about this?

**Comment by birkskyum** [comment]
My motivation was to share a hint how to make the error go away at least temporarily, and also have a place to collect information about whether this is on our side or on jest's side.

**Comment by birkskyum** [comment]
Let's close it for now, and it case we find a way to reproduce it, or make it actionable in some way, we can always reopen. This hint about clearing cache should be searchable still.

**Comment by birkskyum** [comment]
Still present in 2.4.0
