### ISSUE TITLE
Using addLayer's (osm map, canvas) rather than Model.style for both, causes Maximum call stack size exceeded

### ISSUE THREAD

**Issue by backspaces** [maplibre/maplibre-gl-js#1669]
**maplibre-gl-js version**: latest

**browser**: chrome 105.0.5195.52

### Steps to Trigger Behavior

I ran into failures with a canvas layer when using addLayer rather than the style within the Map ctor. I simplified the actual project to two simple "hello" pages. The first places all layers and sources in the Map constructor's style while the second has an empty style in Map's constructor and two addLayers.

![Snap 09 20 22-12 02 43](https://user-images.githubusercontent.com/124366/191331519-054c264f-dbad-449a-9230-98969b68d544.jpg)

 1. Run http://backspaces.net/temp/hello.html. Should work fine
 2. Run http://backspaces.net/temp/hello1.html. Fails with:
 3. maplibre-gl.js:92 Uncaught RangeError: Maximum call stack size exceeded
    at c (maplibre-gl.js:92:17)
    at p (maplibre-gl.js:105:78)
    at c (maplibre-gl.js:95:23)
    at p (maplibre-gl.js:105:78)
    at c (maplibre-gl.js:95:23)
    at p (maplibre-gl.js:105:78)
    at c (maplibre-gl.js:95:23)
    at p (maplibre-gl.js:105:78)
    at c (maplibre-gl.js:95:23)
    at p (maplibre-gl.js:105:78)
 

### Link to Demonstration
http://backspaces.net/temp/hello.html
http://backspaces.net/temp/hello1.html

hello uses:

        const map = new maplibregl.Map({
            container: 'map', // container id
            center: center,
            zoom: 6,

            style: {
                "version": 8,
                sources: {
                    osm: {
                        type: 'raster',
                        tiles: ['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'],
                        tileSize: 256,
                        maxzoom: 19,
                        attribution: '&copy; OpenStreetMap Contributors',
                    },
                    canvas: {
                        type: 'canvas',
                        canvas: canvas,
                        coordinates: bboxCoords(bbox),
                    },
                },
                layers: [
                    {
                        id: 'osm',
                        type: 'raster',
                        source: 'osm'
                    },
                    {
                        id: 'canvas',
                        type: 'raster',
                        source: 'canvas'
                    },
                ]
            },
        })
        await mapLoadPromise(map)

while hello1 uses:

        const map = new maplibregl.Map({
            container: 'map', // container id
            center: center,
            zoom: 6,

            style: {
                "version": 8,
                sources: {},
                layers: []
            },
        })
        await mapLoadPromise(map)

        map.addLayer({
            id: 'osm',
            type: 'raster',
            source: {
                type: 'raster',
                tiles: ['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'],
                tileSize: 256,
                maxzoom: 19,
                attribution: '&copy; OpenStreetMap Contributors',
            },
        })
        map.addLayer({
            id: 'canvas',
            type: 'raster',
            source: {
                type: 'canvas',
                canvas: canvas,
                coordinates: bboxCoords(bbox),
            }
        })

where mapLoadPromise is

        async function mapLoadPromise(map) {
            return new Promise((resolve, reject) => {
                map.on('load', () => resolve())
            })
        }

### Expected Behavior

Both hello and hello1 should show a simple map with a canvas at the specified geolocation:

![Snap 09 20 22-12 13 40](https://user-images.githubusercontent.com/124366/191333245-82eb779c-cc14-45ad-9f87-e72a60d8392d.jpg)

### Actual Behavior

The hello example works as it should, while the hello1 example results with 

        maplibre-gl.js:92 Uncaught RangeError: Maximum call stack size exceeded

**Comment by HarelM** [comment]
The links are not working for me.
Can you share jsbin/codepen/stackblitz links please?

**Comment by HarelM** [comment]
I've looked at the code, and while I'm not sure this is the cause for this issue the two call are not exactly the same.
In hello (the one that works) you define the sources in the style and reference them in the layers with their IDs.
In hello1 (which doesn't work) you define the source in the layer and add the layer with the source at the "same pass".
I believe this is what creates the issue as I think the layer is not cloned well.
It might be a bug, don't get me wrong, but this is not identical behavior. :-)

Using the following code works as expected 
```js
...
map.addSource('c1', {
    type: 'canvas',
    canvas: canvas,
    coordinates: bboxCoords(bbox),
});
map.addLayer({
    id: 'canvas',
    type: 'raster',
    source: 'c1'
})
...
```

**Comment by backspaces** [comment]
Yes indeed: this works as you mentioned:

        map.addSource('osm', {
            type: 'raster',
            tiles: ['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'],
            tileSize: 256,
            maxzoom: 19,
            attribution: '&copy; OpenStreetMap Contributors',

        })
        map.addLayer({
            id: 'osm',
            type: 'raster',
            source: 'osm',
        })

        map.addSource('canvas', {
            type: 'canvas',
            canvas: canvas,
            coordinates: bboxCoords(bbox),

        })
        map.addLayer({
            id: 'canvas',
            type: 'raster',
            source: 'canvas'
        })

So apparently it is a best practice to not use the source directly in the layer, but to define a source and layer pair.

A documentation issue?

**Comment by backspaces** [comment]
Here's the page with this solution: http://backspaces.net/temp/hello2.html

**Comment by HarelM** [comment]
>A documentation issue?

To some extend I guess, you can add a source using add layer but I think this source has to be a plain JS object without any methods, which is not the case here.
I haven't dug into the code to see the actual reason, but the `clone` in `addLayer` when `source` is an object looks suspicious.
Feel free to try and fix this :-) either in the code or in the docs.
