### ISSUE TITLE
map.fitBounds throws outside of bounds error when terrain, center and zoom set and bounds to fit on other side of AM

### ISSUE THREAD

**Issue by llambanna** [maplibre/maplibre-gl-js#2095]
**maplibre-gl-js version**: 3.0.0-pre.3

**browser**:  chrome Version 109.0.5414.87 (Official Build) (x86_64)
 
### Steps to Trigger Behavior

 1. include `center` and `zoom` when instantiate map
 2. include terrain 
 3. use `fitBounds` to move to area the other side of AM from current location

### Link to Demonstration

click on the Fit to NZ button and error throws

https://jsbin.com/qevebesote/edit?html,output

### Expected Behavior

it zooms to NZ

### Actual Behavior

it throws an error:

> maplibre-gl-dev.js:29359 Uncaught Error: x=-7, y=320, z=9 outside of bounds. 0<=x<512, 0<=y<512 0<=z<=25 
    at new CanonicalTileID (maplibre-gl-dev.js:29359:19)
    at new OverscaledTileID (maplibre-gl-dev.js:29407:26)
    at Transform.getElevation (maplibre-gl-dev.js:45892:24)
    at Map._prepareElevation (maplibre-gl-dev.js:49563:48)
    at Map.flyTo (maplibre-gl-dev.js:49781:18)
    at Map._fitInternal (maplibre-gl-dev.js:49338:18)
    at Map.fitBounds (maplibre-gl-dev.js:49295:21)
    at HTMLButtonElement.<anonymous> (runner:49:13)

**Comment by HarelM** [comment]
Thanks for taking the time to report this! Seems like an issue with getting the elevation, maybe missing a wrap of some sort...
