### ISSUE TITLE
Error running performance benchmark

### ISSUE THREAD

**Issue by ZeLonewolf** [maplibre/maplibre-gl-js#2122]
The [performance benchmark](https://github.com/maplibre/maplibre-gl-js/blob/2cfacce6c57a91fcc2ac4102dc665f45224bf805/test/bench/README.md) hangs with errors.

**maplibre-gl-js version**: Current main revision

### Steps to Trigger Behavior
 1. At the console, run `MAPLIBRE_STYLES=https://zelonewolf.github.io/openstreetmap-americana/style.json npm run start-bench`
 2. Observe output in the console
 3. Go to http://localhost:9966/test/bench/styles/index.html -- nothing happens

### Expected Behavior
Performance benchmark reports no errors and user can run performance benchmarks in a web browser as specified in the [docs](https://github.com/maplibre/maplibre-gl-js/blob/2cfacce6c57a91fcc2ac4102dc665f45224bf805/test/bench/README.md).

### Actual Behavior
Performance benchmark hangs with errors:

```
> maplibre-gl@3.0.0-pre.3 start-bench
> run-p watch-css watch-benchmarks start-server


> maplibre-gl@3.0.0-pre.3 watch-benchmarks
> rollup --configPlugin @rollup/plugin-typescript -c test/bench/rollup_config_benchmarks.ts --watch


> maplibre-gl@3.0.0-pre.3 watch-css
> postcss --watch -o dist/maplibre-gl.css src/css/maplibre-gl.css


> maplibre-gl@3.0.0-pre.3 start-server
> st --no-cache -H 0.0.0.0 --port 9966 .

listening at http://0.0.0.0:9966
[!] RollupError: Rollup transpiled your configuration to an  ES module even though it appears to contain CommonJS elements. To resolve this, you can pass the "--bundleConfigAsCjs" flag to Rollup or change your configuration to only contain valid ESM code.

Original error: require is not defined in ES module scope, you can use import instead
https://rollupjs.org/guide/en/#--bundleconfigascjs
ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///home/brian/git/maplibre-gl-js/test/bench/rollup.config-1675192292098.mjs:75:29
    at Array.map (<anonymous>)
    at file:///home/brian/git/maplibre-gl-js/test/bench/rollup.config-1675192292098.mjs:75:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at loadConfigFromWrittenFile (/home/brian/git/maplibre-gl-js/node_modules/rollup/dist/shared/loadConfigFile.js:487:17)
    at getConfigFileExport (/home/brian/git/maplibre-gl-js/node_modules/rollup/dist/shared/loadConfigFile.js:410:20)
    at Object.loadConfigFile (/home/brian/git/maplibre-gl-js/node_modules/rollup/dist/shared/loadConfigFile.js:391:59)
```

**Comment by zhangyiatmicrosoft** [comment]
It will be very helpful to create a bench-sanity test which will execute one pass and really fast to make sure it always work, and add to CI.

**Comment by HarelM** [comment]
There is an issue about it basically: #982 it's harder than it looks...
