### ISSUE TITLE
Failure installing local maplibre-gl-js / maplibre-style-spec

### ISSUE THREAD

**Issue by ZeLonewolf** [maplibre/maplibre-gl-js#2757]
I am experiencing failures linking osm-americana against locally-compiled copies of maplibre-gl-js and maplibre-style-spec. I don't know if this this is an Americana problem, a gl-js problem, or a style-spec problem so I'm looking for help on how to troubleshoot this.

**maplibre-gl-js version**: latest commit as of 28 June 2023

### Steps to Trigger Behavior

 1. Check out and build maplibre-gl-js and maplibre-style-spec:

```
git clone git@github.com:maplibre/maplibre-style-spec.git
git clone git@github.com:maplibre/maplibre-gl-js.git
cd maplibre-style-spec
nvm install
npm install
npm run build
npm run test-unit
cd ..
cd maplibre-gl-js
nvm install
npm install
npm run build-dist
cd ..
```

 2. Build project that uses maplibre-gl-js. We'll use OSM Americana for this example:
```
git clone git@github.com:ZeLonewolf/openstreetmap-americana.git
cd openstreetmap-americana
npm install
```
 3. npm install the locally-compiled maplibre-gl-js:
```
npm install ../maplibre-gl-js
```

### Link to Demonstration

The procedure above results in an error, with the following log output:
[2023-06-28T22_40_43_724Z-debug-0.log](https://github.com/maplibre/maplibre-gl-js/files/11900466/2023-06-28T22_40_43_724Z-debug-0.log)

### Expected Behavior

`npm install` command succeeds and project builds against the local maplibre-gl-js.

### Actual Behavior

`npm install` command fails with the following output ([full log](https://github.com/maplibre/maplibre-gl-js/files/11900466/2023-06-28T22_40_43_724Z-debug-0.log)):

```
155 error /home/brian/git/maplibre-gl-js/node_modules/ts-node/src/index.ts:859
155 error     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
155 error            ^
155 error TSError: ⨯ Unable to compile TypeScript:
155 error ../maplibre-style-spec/dist/index.cjs(3,10): error TS2304: Cannot find name 'define'.
155 error ../maplibre-style-spec/dist/index.cjs(3,35): error TS2304: Cannot find name 'define'.
155 error ../maplibre-style-spec/dist/index.cjs(3,48): error TS2304: Cannot find name 'define'.
155 error ../maplibre-style-spec/dist/index.cjs(4,4): error TS2322: Type 'typeof globalThis | typeof import("/home/brian/git/maplibre-style-spec/dist/index")' is not assignable to type 'typeof import("/home/brian/git/maplibre-style-spec/dist/index")'.
155 error   Type 'typeof globalThis' is missing the following properties from type 'typeof import("/home/brian/git/maplibre-style-spec/dist/index")': Color, ColorType, CompoundExpression, EvaluationContext, and 41 more.
155 error ../maplibre-style-spec/dist/index.cjs(4,93): error TS2339: Property 'maplibreGlStyleSpecification' does not exist on type 'typeof import("/home/brian/git/maplibre-style-spec/dist/index")'.
155 error ../maplibre-style-spec/dist/index.cjs(4,135): error TS2339: Property 'UnitBezier' does not exist on type 'typeof import("/home/brian/git/maplibre-style-spec/dist/index")'.
155 error ../maplibre-style-spec/dist/index.cjs(3057,20): error TS2552: Cannot find name 'Layer'. Did you mean 'layer'?
155 error ../maplibre-style-spec/dist/index.cjs(3058,22): error TS2552: Cannot find name 'Layer'. Did you mean 'layer'?
155 error ../maplibre-style-spec/dist/index.cjs(3388,31): error TS1016: A required parameter cannot follow an optional parameter.
155 error ../maplibre-style-spec/dist/index.cjs(3838,35): error TS2345: Argument of type 'number[]' is not assignable to parameter of type '[any, any, any, any]'.
155 error   Target requires 4 element(s) but source may have fewer.
155 error ../maplibre-style-spec/dist/index.cjs(4076,32): error TS2556: A spread argument must either have a tuple type or be passed to a rest parameter.
155 error ../maplibre-style-spec/dist/index.cjs(4159,79): error TS2322: Type 'string' is not assignable to type '"variant" | "case" | "accent" | "base"'.
155 error ../maplibre-style-spec/dist/index.cjs(4687,17): error TS8032: Qualified name 'options.omitTypeAnnotations' is not allowed without a leading '@param {object} options'.
155 error ../maplibre-style-spec/dist/index.cjs(5204,49): error TS2339: Property 'definitions' does not exist on type 'typeof CompoundExpression'.
155 error ../maplibre-style-spec/dist/index.cjs(5231,51): error TS2341: Property 'parse' is private and only accessible within class 'ParsingContext'.
155 error ../maplibre-style-spec/dist/index.cjs(5245,40): error TS2341: Property 'error' is private and only accessible within class 'ParsingContext'.
155 error ../maplibre-style-spec/dist/index.cjs(5252,36): error TS2341: Property 'concat' is private and only accessible within class 'ParsingContext'.
155 error ../maplibre-style-spec/dist/index.cjs(5280,30): error TS2339: Property 'definitions' does not exist on type 'typeof CompoundExpression'.
155 error ../maplibre-style-spec/dist/index.cjs(7424,29): error TS2341: Property 'parse' is private and only accessible within class 'ParsingContext'.
155 error ../maplibre-style-spec/dist/index.cjs(7675,20): error TS2322: Type '{ filter: () => boolean; needGeometry: boolean; }' is not assignable to type 'Function'.
155 error   Object literal may only specify known properties, and 'filter' does not exist in type 'Function'.
155 error ../maplibre-style-spec/dist/index.cjs(7686,20): error TS2322: Type '{ filter: (globalProperties: any, feature: any, canonical: any) => any; needGeometry: boolean; }' is not assignable to type 'Function'.
155 error   Object literal may only specify known properties, and 'filter' does not exist in type 'Function'.
155 error ../maplibre-style-spec/dist/index.cjs(8101,31): error TS2345: Argument of type 'any[]' is not assignable to parameter of type 'string'.
155 error ../maplibre-style-spec/dist/index.cjs(8206,23): error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'string'.
155 error ../maplibre-style-spec/dist/index.cjs(8308,20): error TS2552: Cannot find name 'Layer'. Did you mean 'layer'?
155 error ../maplibre-style-spec/dist/index.cjs(8310,28): error TS2552: Cannot find name 'Layer'. Did you mean 'layer'?
155 error ../maplibre-style-spec/dist/index.cjs(8953,27): error TS2339: Property 'ref' does not exist on type 'never'.
155 error ../maplibre-style-spec/dist/index.cjs(8957,38): error TS2339: Property 'type' does not exist on type 'never'.
155 error
155 error     at createTSError (/home/brian/git/maplibre-gl-js/node_modules/ts-node/src/index.ts:859:12)
155 error     at reportTSError (/home/brian/git/maplibre-gl-js/node_modules/ts-node/src/index.ts:863:19)
155 error     at getOutput (/home/brian/git/maplibre-gl-js/node_modules/ts-node/src/index.ts:1077:36)
155 error     at Object.compile (/home/brian/git/maplibre-gl-js/node_modules/ts-node/src/index.ts:1433:41)
155 error     at Module.m._compile (/home/brian/git/maplibre-gl-js/node_modules/ts-node/src/index.ts:1617:30)
155 error     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
155 error     at Object.require.extensions.<computed> [as .js] (/home/brian/git/maplibre-gl-js/node_modules/ts-node/src/index.ts:1621:12)
155 error     at Module.load (node:internal/modules/cjs/loader:1037:32)
155 error     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
155 error     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29) {
155 error   diagnosticCodes: [
155 error     2304, 2304, 2304, 2322, 2339,
155 error     2339, 2552, 2552, 1016, 2345,
155 error     2556, 2322, 8032, 2339, 2341,
155 error     2341, 2341, 2339, 2341, 2322,
155 error     2322, 2345, 2345, 2552, 2552,
155 error     2339, 2339
155 error   ]
155 error }
155 error ERROR: "generate-style-code" exited with 1.
```

**Comment by ZeLonewolf** [comment]
I've also tested this against https://github.com/maplibre/maplibre-gl-compare/ and gotten the same error message.

**Comment by HarelM** [comment]
I don't think this will work as described.
The package that is published to npm is not the same as the folder, some files are excluded.
I would try the following:
npm pack the spec, then install that tar in maplibre-gl then build and pack and then install both in americana.
I have not tried it my self though.
Another option is to simply copy the dist folder of each package to the node_modules folder where they are needed before building.

**Comment by ZeLonewolf** [comment]
Also - I've successfully used `npm i <file location>` against maplibre-gl-js  prior to the split of maplibre-style-spec into its own repo, so this has worked in the past. I'm wondering if something about that split or how style-spec's package is set up is causing the issue.

**Comment by HarelM** [comment]
https://futurestud.io/tutorials/npm-create-a-local-release-package-before-publishing-to-the-registry

**Comment by HarelM** [comment]
Closing this issue, feel free to add some notes to the style-spec readme or here on how to use local version together.
Generally speaking, the easiest way I found so far is simply overrider the dist folder in the relevant node_modules package with the compiled code.
In this case:
build the style-spec
copy the dist into maplibre's node_modules style-spec dist folder
build maplibre-gl-js
copy the dist into where you need it (OSM americana, maputnik, ngx-maplibre-gl, etc).
