### ISSUE TITLE
Error rendering large number of icon symbols

### ISSUE THREAD

**Issue by lucas-oliveira-viana** [maplibre/maplibre-gl-js#2891]
**maplibre-gl-js version**: 3.2.0

**browser**: Chrome version 114.0.5735.198

### Steps to Trigger Behavior

 1. Create a source
 2. Create a symbol icon type layer
 3. Add more than 32768 points close to each other
 4. When interact on map, will show the following console error:
 `Uncaught Error: bucket.icon.opacityVertexArray.length (= 32768) !== bucket.icon.layoutVertexArray.length (= 183076) / 4
    at Placement.updateBucketOpacities (placement.ts:1144:103)
    at Placement.updateLayerOpacities (placement.ts:936:22)
    at Style._updatePlacement (style.ts:1548:32)
    at Map._render (map.ts:3089:57)
    at map.ts:3225:22`

### Link to Demonstration

Zoom out and then zoom in for throw console error (error occurs on zoom 9-)

https://jsbin.com/dawojeluxu/1/edit?html,js,output

### Expected Behavior

Symbols render normally without errors

### Actual Behavior

Symbols are not rendering

**Comment by HarelM** [comment]
According to the error is seems like a limitation of the library/webgl...
Feel free to pursue the big fix 😀

**Comment by jokroese** [comment]
I'm getting the same issue (MapLibre: 3.6.2). To recreate the error, you can also go here: https://deploy-preview-3--queeringthemap.netlify.app/ and zoom out(!).

@HarelM what makes you say it is related to WebGL? The error doesn't mention anything about it and points to a mismatch in arrays in MapLibre's code ([placement.ts:1156:102](https://github.com/maplibre/maplibre-gl-js/blob/981a51b608fc0a0cf4341cd303e7a4af572e776e/src/symbol/placement.ts#L1156)).

Based on @lucas-oliveira-viana's report, the error seems to occur whenever:

1. there are more than 32768 points on screen
1. shown through a layer of type 'symbol'

**Comment by jokroese** [comment]
I haven't tried implementing it yet, but I think the issue might be with MapLibre's implementation of WebGL's `gl.drawElement` here in [src/render/program.ts](https://github.com/maplibre/maplibre-gl-js/blob/981a51b608fc0a0cf4341cd303e7a4af572e776e/src/render/program.ts#L229C26-L229C26):

```javascript
gl.drawElements(
                drawMode,
                segment.primitiveLength * primitiveSize,
                gl.UNSIGNED_SHORT,
                segment.primitiveOffset * primitiveSize * 2);
```

Note that it uses `gl.UNSIGNED_SHORT` which is [limited to values [0, 62353]](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/vertexAttribPointer#type).

If that's the issue, we could replace it with `gl.UNSIGNED_INT` which is 32-bit. To do this, we would need to use the [OES_element_index_uint extension](https://developer.mozilla.org/en-US/docs/Web/API/OES_element_index_uint) which is part of the WebGL API.

**Comment by jokroese** [comment]
In the meantime, we can avoid MapLibre's current limitation by chunking the data into groups of 32768.

```js
export function chunkData(geojson, chunkSize: number) {
    if (geojson.type !== 'FeatureCollection') {
        throw new Error("Input must be a GeoJSON FeatureCollection");
    }

    const chunks = [];
    for (let i = 0; i < geojson.features.length; i += chunkSize) {
        chunks.push({
            type: 'FeatureCollection',
            features: geojson.features.slice(i, i + chunkSize),
        });
    }

    return chunks;
}
```

then the chunks like this:

```js
const dataChunks = chunkData(large_data, 32768);

dataChunks.forEach((chunk, index) => {
  const sourceId = `moments-${index}`;
  const layerId = `moments-layer-${index}`;

  map.addSource(sourceId, {
    type: 'geojson',
	data: chunk
  });
    
  // whatever else we want to do
}
```

**Comment by PanierAvide** [comment]
A little 2025 update : this still happens with MapLibre 5.6.0. For example : https://viewer.geovisio.fr/viewer.html?background=streets&focus=map&map=19.24/48.1190651/-1.6120557&speed=250&theme=default

In this example, the source is `vector` type, with an icon symbol layer. I'm wondering if there is a workaround to limit the amount of symbols to display from vector tiles client-side, or this is something to handle server-side.

**Comment by mkeller3** [comment]
> A little 2025 update : this still happens with MapLibre 5.6.0. For example : https://viewer.geovisio.fr/viewer.html?background=streets&focus=map&map=19.24/48.1190651/-1.6120557&speed=250&theme=default
> 
> In this example, the source is `vector` type, with an icon symbol layer. I'm wondering if there is a workaround to limit the amount of symbols to display from vector tiles client-side, or this is something to handle server-side.

I am still seeing this issue as well in `5.6.2`

**Comment by BoBoDinachen** [comment]
I also encountered this issue in version 5.24.0. Is there a solution?

**Comment by HarelM** [comment]
In the prerelease of version 6 we have set the default for `experimentalzoomlevelstooverscale` to 4
https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/MapOptions/#experimentalzoomlevelstooverscale

You should be able to use it with 5.24.0 as well, I'm not sure it will solve the problem though, but it might help.
Having said that, if you are trying to render more than 32k icons in the same place I would recommend trying to improve the data processing pipeline to avoid this...

**Comment by BoBoDinachen** [comment]
> In the prerelease of version 6 we have set the default for `experimentalzoomlevelstooverscale` to 4 https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/MapOptions/#experimentalzoomlevelstooverscale
> 
> You should be able to use it with 5.24.0 as well, I'm not sure it will solve the problem though, but it might help. Having said that, if you are trying to render more than 32k icons in the same place I would recommend trying to improve the data processing pipeline to avoid this...

Thank you very much! After trying to modify the values of the `experimentalZoomLevelsToOverscale `and `maxZoom `parameters, the problem seems to have been resolved.
