### ISSUE TITLE
Map tile rendering failure due to CSS color syntax validation error (fixed in maplibre-style-spec 19.3.0)

### ISSUE THREAD

**Issue by hy9be** [maplibre/maplibre-gl-js#2893]
**maplibre-gl-js version**: 3.2.0

**browser**: Chrome/Firefox/Edge/Safari

**Note this is a regression issue from 2.x.** maplibre-style-spec 19.3.0 released yesterday fixed this issue: https://github.com/maplibre/maplibre-style-spec/commit/53186c4d2852c69d4afeeb6a2428b734060a5492. But the latest 3.2.x version is still using 19.2.2. Suggest we make a 3.2.1 release to pick up the fix.

### Steps to Trigger Behavior

 1. Load a map style including leading spaces in CSS color expressions. The spaces fails the style validation thus fails the tile rendering.

### Expected Behavior
Map tiles are not rendered with the error in Console:
```
Error: layers[256].paint.text-halo-color: color expected, " rgba(240,247,244,0.4)" found
    at Object.An [as emitValidationErrors] (validate_style.ts:46:41)
    at te (style.ts:41:26)
    at ae._load (style.ts:343:33)
    at style.ts:321:22
    at ajax.ts:180:13
```

### Actual Behavior
Map tiles should still be rendered without issues

**Comment by hy9be** [comment]
Yes. Confirmed that in my local environment.
