### ISSUE TITLE
App using terrain (raster-dem) crashes when zooming out after zooming in quickly

### ISSUE THREAD

**Issue by uxduck** [maplibre/maplibre-gl-js#3982]
**maplibre-gl-js version**: 4.1.2

**browser**:
- Firefox 124.0.2 (64-bit)
- Chrome Version 123.0.6312.107 (Official Build) (arm64)

### Overview

I've got an app that uses terrain (raster-dem) as following https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/, but it consistently crashes when zooming out after zooming in quickly. It has different errors depending on the browser.

On Firefox, crashes with
```
TypeError: this._tiles[T] is undefined
    update https://geojsons.com/assets/maplibre-gl-Cb84O7q2.js:5
    _updateSources https://geojsons.com/assets/maplibre-gl-Cb84O7q2.js:5
    _render https://geojsons.com/assets/maplibre-gl-Cb84O7q2.js:580
    _render https://geojsons.com/assets/index-DPuhvsxQ.js:40
    redraw https://geojsons.com/assets/index-DPuhvsxQ.js:40
    setProps https://geojsons.com/assets/index-DPuhvsxQ.js:40
    nue https://geojsons.com/assets/index-DPuhvsxQ.js:40
    gT https://geojsons.com/assets/index-DPuhvsxQ.js:40
    d6 https://geojsons.com/assets/index-DPuhvsxQ.js:40
    EX https://geojsons.com/assets/index-DPuhvsxQ.js:40
    wle https://geojsons.com/assets/index-DPuhvsxQ.js:40
```

On Chrome, crashes with:
```
index-DPuhvsxQ.js:40 TypeError: Cannot read properties of undefined (reading 'clearFadeHold')
    at Wt.update (maplibre-gl-Cb84O7q2.js:5:316045)
    at Ci._updateSources (maplibre-gl-Cb84O7q2.js:5:378798)
    at k.Map._render (maplibre-gl-Cb84O7q2.js:580:203711)
    at s._render (index-DPuhvsxQ.js:40:64095)
    at jA.redraw (index-DPuhvsxQ.js:40:64985)
    at jA.setProps (index-DPuhvsxQ.js:40:62928)
    at index-DPuhvsxQ.js:40:70798
    at gT (index-DPuhvsxQ.js:40:24296)
    at d6 (index-DPuhvsxQ.js:40:31641)
    at EX (index-DPuhvsxQ.js:40:31497)
```

I tried to create a reproducible example with example in https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/, but I found a slightly different issue. I just created an `index.html` containing the HTML snippet, and replaced the `url` for `terrainSource` and `hillshadeSource` with `https://api.maptiler.com/tiles/terrain-rgb/tiles.json?key=MY_KEY_FROM_MAPTILER`. Zooming in/out in that one will crash with:

```
Uncaught Error: Invalid LngLat object: (NaN, NaN)
    Gu lng_lat.ts:63
    toLngLat mercator_coordinate.ts:126
    coordinateLocation transform.ts:584
    pointLocation transform.ts:565
    unproject map.ts:1166
    Es events.ts:527
    mousemove map_event.ts:122
    handleEvent handler_manager.ts:391
    addEventListener dom.ts:62
    _a handler_manager.ts:209
    <anonymous> map.ts:633
    <anonymous> index.html:18
```

### Steps to Trigger Behavior

 1. Zoom in quickly, then
 2. Zoom out quickly

There are other ways to reproduce this, like programmatically setting the view state to a high zoom, and them zooming out. But the simplest 

It seems like zooming in quickly, or programmatically will be too quick for maplibre to download all the terrain data. It then crashes when zooming out, and can't find it.

### Link to Demonstration

Just zoom in and out quickly on https://geojsons.com/. Commenting out https://github.com/ben-xD/geojsons/blob/6f13536abb8e52beb9bded1095501cefc4d13220/frontend/src/map/GeojsonsMap.tsx#L352-L358 will fix the crashing. It seems like using `raster-dem` / terrain causes this issue.

### Expected Behavior

No crashing. Zoom in/out works.

### Actual Behavior

App crashes when zooming out.

if anyone could suggest a workaround or a fix, I would be grateful. Thanks 

### Workaround

Disable terrain completely.

**Comment by HarelM** [comment]
I can't reproduce this when using the example page on a macos with chrome:
https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/

Can you try and create a jsbin that reproduces this?
Since geojsons.com might have some wrapper library that can cause issues I prefer to have a jsbin without any wrappers that reproduces this issue.
It's also worth trying to see if you can find a version that this bug doesn't happen in, so we can maybe find the relevant PR that caused this issue (assuming it was there from the initial introduction of the terrain code).

**Comment by ben-xD** [comment]
Hey @Harel, 

I'll investigate further on the first error (`TypeError: this._tiles[T] is undefined`) which impacts me and happens almost instantly when i zoom in/out quickly. I'll try create a reproducible example. 

However, for the demo crashing, did you try a non-demo terrain url? I was able to reproduce the error using [maplibre.org/maplibre-gl-js/docs/examples/3d-terrain](https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/), as long as I used maptiler's tiles. Or just update `MY_KEY_FROM_MAPTILER` in https://jsbin.com/romekiriho/1/edit?html,output to be your free Maptiler API key. 

Here's a 15s video that is 2x speed of me just zooming in and out, and eventually the app crashes. So it took about 30 seconds, less problematic that the original error.


https://github.com/maplibre/maplibre-gl-js/assets/24711048/fba24629-4454-4ee6-b2a0-05d1c60d0e0f



I've also attached the html file, just update `MY_KEY_FROM_MAPTILER`

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>3D Terrain</title>
    <meta property="og:description" content="Go beyond hillshade and show elevation in actual 3D." />
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='https://unpkg.com/maplibre-gl@4.1.2/dist/maplibre-gl.css' />
    <script src='https://unpkg.com/maplibre-gl@4.1.2/dist/maplibre-gl.js'></script>
    <style>
        body { margin: 0; padding: 0; }
        html, body, #map { height: 100%; }
    </style>
</head>
<body>
<div id="map"></div>
<script>
    const key = "MY_KEY_FROM_MAPTILER"
    const map = (window.map = new maplibregl.Map({
        container: 'map',
        zoom: 12,
        center: [11.39085, 47.27574],
        pitch: 52,
        hash: true,
        style: {
            version: 8,
            sources: {
                osm: {
                    type: 'raster',
                    tiles: ['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'],
                    tileSize: 256,
                    attribution: '&copy; OpenStreetMap Contributors',
                    maxzoom: 19
                },
                // Use a different source for terrain and hillshade layers, to improve render quality
                terrainSource: {
                    type: 'raster-dem',
                    url: `https://api.maptiler.com/tiles/terrain-rgb/tiles.json?key=${key}`,
                    tileSize: 256
                },
                hillshadeSource: {
                    type: 'raster-dem',
                    url: `https://api.maptiler.com/tiles/terrain-rgb/tiles.json?key=${key}`,
                    tileSize: 256
                }
            },
            layers: [
                {
                    id: 'osm',
                    type: 'raster',
                    source: 'osm'
                },
                {
                    id: 'hills',
                    type: 'hillshade',
                    source: 'hillshadeSource',
                    layout: {visibility: 'visible'},
                    paint: {'hillshade-shadow-color': '#473B24'}
                }
            ],
            terrain: {
                source: 'terrainSource',
                exaggeration: 1
            }
        },
        maxZoom: 18,
        maxPitch: 85
    }));

    map.addControl(
        new maplibregl.NavigationControl({
            visualizePitch: true,
            showZoom: true,
            showCompass: true
        })
    );

    map.addControl(
        new maplibregl.TerrainControl({
            source: 'terrainSource',
            exaggeration: 1
        })
    );
</script>
</body>
</html>
```

</details>

**Comment by HarelM** [comment]
The error in the console seems related to matrix inversion if I understand correctly.
I'm no linear algebra expert, but it might be some edge case related to the projection matrix.
I would try and find an easy way to reproduce this, otherwise, you'll have a hard time understanding what causes this.
I'm not able to reproduce it using the terrain 3D demo example page unfortunately...

**Comment by Sumbera** [comment]
I can confirm  this  issue. It is  easily reproducible with my data and with other data too.  MapLibreGL using terrain can relatively easily come with user interaction to the state it is unusable, freezes view, or even can't recover by refreshing page. I can back trace it. Version 4.1 and earlier was the  last version that didn't freeze view or produce errors in console and  behaved acceptably for working with terrain. 

From version 4.1.1 experience with terrain  started to degradate.

I can see too in console:
lng_lat.ts:63 Uncaught Error: Invalid LngLat object: (NaN, NaN)

and following version flood similar errors, the last version 5.3 :
source_cache.ts:751 Uncaught TypeError: Cannot read properties of undefined (reading 'key')
    at de._updateRetainedTiles (source_cache.ts:751:40)
    at de.update (source_cache.ts:670:29)
    at gi._updateSources (style.ts:1655:35)
    at e.Map._render (map.ts:3239:24)
    at map.ts:3393:30

New collision detection probably causing  jumping out of the area so I lose context where I was and I think it jumps for no real collision  reason too.

matrix inversion was also one of the console  logs I have seen. This indicates wrong view state calc from the user input.

*Videos:*
here is how version 5.3  works on my data: https://youtu.be/bFmIXYUE4NU

And here is older version   3.4.0  : https://www.youtube.com/watch?v=ZqPzCDh5lbI
where quite well collision worked  and no freeze, no console error logs, no jumps. It is what happens after version 4.1.0,  and continues in various forms to the latest form.

**Comment by HarelM** [comment]
I think you are mixing too many issue into this bug. 
I believe the errors in the video are related to the following issue, which is different.

**Comment by HarelM** [comment]
Also sending a YouTube video without a link to a code that can reproduce the problem is not very helpful, unless you plan to solve the issue yourself...

**Comment by Sumbera** [comment]
@HarelM thanks for response and warm welcome ! Good points, here it goes - a new video directly from the MapLibreGL sample page : 
https://www.youtube.com/watch?v=FG_udiczye4

the code is here: https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/

let me know if you need any other input. Recorded from Safari 18.1.1. on Mac.

if there is a stable and usable version of MapLibreGL for navigation in terrain above 4.1.0, please point me on it,  I am happy to  test it. So far I can't find it.

**Comment by tim-salabim** [comment]
FWFW, I can reproduce this issue in Firefox 137.0.1 on the help page at https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/ but only at maximum pitch. At lower pitch levels, everything seems to work fine.

**Comment by Sumbera** [comment]
It is not  Safari specific, I can reproduce it on Chrome on Mac too (same sample):
https://www.youtube.com/watch?v=dqotlfnlxMM

**Comment by HarelM** [comment]
It might be related to some scrolling definition, as I can't reproduce it on my mac (at least not when I'm not trying to zoom into the terrain).
In any case, feel free to try and look at the relevant PR and see if you can find a better approach to the provided fix.

**Comment by Sumbera** [comment]
I can reproduce it on Windows /Chrome too. Usually when view ends inside the terrain then further zooming produces jump. So I assume some  wrong state is continuing  to add into calculations for collision. 

I have placed sample on my site with starting location inside the hill. Try then to zoom forward or backward to experience jumping. (on Mac simple swipe two fingers up or down on trackpad, or pinch zoom gesture)

version 5.3:
https://sumbera.com/lab/MapLibreGL/terrain/testTerrain.html#12.53/47.56709/11.58581/47.1/85

here is version 4.1.0 correctly handling it
https://sumbera.com/lab/MapLibreGL/terrain/testTerrain4.1.html#12.53/47.56709/11.58581/47.1/85

**Comment by tygra22** [comment]
Workaround: MapLibre GL JS crashes during rapid zoom
Problem

Rapid zoom in/out operations can trigger crashes with errors like:

TypeError: Cannot read properties of undefined (reading 'key')
    at _updateRetainedTiles (…/maplibre-gl.js:…)

TypeError: Cannot use 'in' operator to search for 've4pbb' in undefined

Likely root cause (hypothesis)

Race conditions in the tile-caching/retention logic: rapid zoom changes leave partially loaded tiles in cache, and later access attempts hit undefined tile objects.

Workaround (mitigation)

Two-pronged approach that prevents most crashes and degrades gracefully if they still occur.

1) Increase tile cache headroom (reduces eviction pressure)
// Example map options (tune to your app)
const map = new maplibregl.Map({
  container: 'map',
  style: '…',
  center: [0, 0],
  zoom: 10,

  // Larger cache + broader retention window
  maxTileCacheSize: 1000,      // store more tiles
  maxTileCacheZoomLevels: 10,  // retain across more zoom deltas
});

2) Defensive monkey-patching (graceful recovery instead of crash)

Wrap the problematic internals with try/catch and clear corrupted state if an exception occurs. Use at your own risk; adjust names for your build.

// Pseudo-code: adapt to your bundler / MapLibre version
// Goal: catch rare errors and reset corrupted caches instead of crashing.

(function patchMapLibre() {
  const anyGL = maplibregl as any;

  const SourceCache = anyGL?.SourceCache?.prototype;
  if (SourceCache) {
    // _updateRetainedTiles
    const _origUpdateRetainedTiles = SourceCache._updateRetainedTiles;
    if (typeof _origUpdateRetainedTiles === 'function') {
      SourceCache._updateRetainedTiles = function (...args: any[]) {
        try {
          return _origUpdateRetainedTiles.apply(this, args);
        } catch (err) {
          console.warn('[MapLibre] _updateRetainedTiles failed; clearing retained tiles', err);
          // Reset suspected corrupted state
          this._retainedTiles = {};
          // Optionally continue without throwing
          return;
        }
      };
    }

    // update (sourceCache.update)
    const _origUpdate = SourceCache.update;
    if (typeof _origUpdate === 'function') {
      SourceCache.update = function (...args: any[]) {
        try {
          return _origUpdate.apply(this, args);
        } catch (err) {
          console.warn('[MapLibre] sourceCache.update failed; clearing tiles state', err);
          this._tiles = {};
          this._retainedTiles = {};
          return;
        }
      };
    }
  }
})();

Result

Suppressed errors logged to console as warnings:

Caught _updateRetainedTiles error: TypeError: Cannot read properties of undefined (reading 'key')
    at xe._updateRetainedTiles (maplibre-gl.js:53:71648)
    at sourceCache._updateRetainedTiles (MapLibreEngine.ts:78:41)
    at sourceCache._updateRetainedTiles (MapLibreEngine.ts:78:41)
    at sourceCache._updateRetainedTiles (MapLibreEngine.ts:78:41)
    at xe.update (maplibre-gl.js:53:70536)
    at sourceCache.update (MapLibreEngine.ts:94:47)
    at sourceCache.update (MapLibreEngine.ts:94:47)
    at sourceCache.update (MapLibreEngine.ts:94:47)
    at wi._updateSources (maplibre-gl.js:53:296157)
    at e.Map._render (maplibre-gl.js:55:81383)
sourceCache._updateRetainedTiles @ MapLibreEngine.ts:80
MapLibreEngine.ts:96 Caught sourceCache update error: TypeError: Cannot use 'in' operator to search for '3hk0hcc' in undefined
    at t.am (maplibre-gl.js:48:37207)
    at xe.update (maplibre-gl.js:53:70692)
    at sourceCache.update (MapLibreEngine.ts:94:47)
    at sourceCache.update (MapLibreEngine.ts:94:47)
    at sourceCache.update (MapLibreEngine.ts:94:47)
    at wi._updateSources (maplibre-gl.js:53:296157)
    at e.Map._render (maplibre-gl.js:55:81383)
    at eval (maplibre-gl.js:55:84122)
    at eval (maplibre-gl.js:53:358)

No hard crashes during rapid zoom.

Performance remains good: larger cache reduces the chance of hitting the race.

If an edge case still occurs, warnings are logged and the map recovers gracefully.

Notes

This is a workaround for what appears to be an upstream race in tile management.

A proper fix likely requires synchronization/state-consistency changes in the core library.

**Comment by larsmaxfield** [comment]
Running into this problem as well.

Crashes consistently when `renderWorldCopies=false` and fully zoomed out.

@Sumbera pointed out 4.3.0 is seemingly fixed. I can confirm specifically that 4.1.0 and older have this issue, then 4.1.1 onwards is fine until 5.0.0:

- [4.1.0 (broken)](https://larsmaxfield.com/swings/maplibre/out-of-bounds-pitched-terrain/4.1.0/)
- [4.1.1 (fixed)](https://larsmaxfield.com/swings/maplibre/out-of-bounds-pitched-terrain/4.1.1/)
- [5.0.0 (broken again)](https://larsmaxfield.com/swings/maplibre/out-of-bounds-pitched-terrain/5.0.0/)
- [latest (still broken)](https://larsmaxfield.com/swings/maplibre/out-of-bounds-pitched-terrain/)

And indeed when not over terrain, there's no issue:

- https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain.html#0/0/0/-28/70

Tested on Windows 11:
- Microsoft Edge 140.0.3485.54 (Official build) (64-bit)
- Mozilla Firefox 142.0.1 (64-bit)

**Comment by kodeezabdullah** [comment]
Hi, I'd like to investigate and work on this issue.
From the comments, it appears to be a regression introduced  in v5.0.0, since v4.1.1 had this working correctly. 
I'll start by diffing the changes between those versions in `source_cache.ts` and `terrain.ts` to identify 
what broke the tile retention logic. Will update here with findings.
Could you please assign this issue to me @HarelM

**Comment by Sumbera** [comment]
@kodeezabdullah thanks  !  I can provide you my data set (large DEM model) for testing, if you are interested. There are many other issues on the terrain - performance, tile num payload, quality, terrain cracks - all of that seemed to degrade from the v4.1.1 and more bugs introduced (like jumps of the camera in 5.20).  
Tricky part is also setSourceTileLodParams - that seems impossible to set correctly to balance quality vs payload.For some reasons 4.1.1 had it  balanced better as default.

**Comment by kodeezabdullah** [comment]
Hi @Sumbera ! Thank you so much for the offer.I would really appreciate having your DEM dataset 
for testing, it would be extremely helpful for reproducing and validating the fix.
You've raised some very interesting points about the regression from v4.1.1. My plan is to start 
by diffing the changes between v4.1.1 and v5.0.0 in source_cache.ts and terrain.ts to identify 
exactly what broke.
Would love to stay in touch as I investigate . your insights from real world terrain usage will 
be invaluable. Please feel free to share the dataset whenever convenient!

**Comment by HarelM** [comment]
Assigned, good luck!

**Comment by kodeezabdullah** [comment]
Hey @HarelM !
After digging into this, turns out the crash paths from this issue (this._tiles[T] is undefined, 
clearFadeHold on undefined, Invalid LngLat (NaN, NaN)) were already removed as part of the tile_manager refactor. The bug doesn't reproduce on current main anymore.
I've opened a PR that adds a regression test to confirm this and guard against it coming back:
#7754
Happy to close this issue out if you agree it's resolved!

**Comment by HarelM** [comment]
Thanks for looking into this!
I've added a small comment in the PR.

**Comment by johncarmack1984** [comment]
The unguarded _tiles[key].hasData() that threw here was removed by #6446 (v5.8.0); #7754 is the test that was meant to guard it. This one can be closed.

**Comment by johncarmack1984** [comment]
to further explain per @HarelM's Q on #8320: Two different crashes have been reported here, and the earlier comment only covered the first.

The original 2024 report (`this._tiles[T] is undefined` in the retained-tiles loop) went away with #6446 in v5.8.0.

The one @larsmaxfield reported in November 2025 (renderWorldCopies false, pitched terrain, zooming out at zoom 0) is a different path: `Error: x=0, y=-1, z=0 outside of bounds` thrown from the terrain elevation lookup, as an unhandled rejection during the zoom. 

Driving that exact setup with a script (drags past the edge, wheel zoom in and out, jumps to the poles and the antimeridian) throws it on 5.0.0 and 5.8.0 and not on 5.24.0, 6.0.0, 6.7.0 or current main (Chrome; main also clean in Firefox 155). 

The guard that ended it is #6775 (`isInBoundsForZoomLngLat` in `getElevationForLngLatZoom`), first released in v5.14.0, after that report. #7754 tests the first path only.

Both paths are gone on current main, so I believe this one is closable.
