### ISSUE TITLE
updateGPUdependent error

### ISSUE THREAD

**Issue by catalinconstant** [maplibre/maplibre-gl-js#4854]
On version 5.0.0-pre.2 and 5.0.0-pre.1 occurred this error  when maplibre initialise 
"Uncaught TypeError: Cannot read properties of undefined (reading 'updateGPUdependent')
    at ys.render (maplibre-gl.js:46:336610)
    at t.Map._render (maplibre-gl.js:46:479423)
    at t.Map.redraw (maplibre-gl.js:46:480368)
    at maplibre-gl.js:46:459691
    at r (maplibre-gl.js:46:356332)
    at maplibre-gl.js:46:356404
    at ResizeObserver.<anonymous> (maplibre-gl.js:46:459755)"

**maplibre-gl-js version**:
5.0.0-pre.2 and 5.0.0-pre.1 
**browser**:
Chrome, Firefox
### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by HarelM** [comment]
There is a template for a reason. Falling to fill it will result in closing the issue.
