### ISSUE TITLE
Cannot read properties of undefined (reading 'transform')

### ISSUE THREAD

**Issue by catdevnull** [maplibre/maplibre-gl-js#4953]
I'm getting this error on my app's Sentry:

```
TypeError: Cannot read properties of undefined (reading 'transform')
  at L.MaplibreGL_transformGL (../../../../node_modules/@maplibre/maplibre-gl-leaflet/leaflet-maplibre-gl.js:202:25)
  at L.MaplibreGL_update (../../../../node_modules/@maplibre/maplibre-gl-leaflet/leaflet-maplibre-gl.js:176:18)
  at wrapperFn (../../../../node_modules/leaflet/dist/leaflet-src.js:100:9)
  at Events.fire (../../../../node_modules/leaflet/dist/leaflet-src.js:606:11)
  at Map._onPanTransitionStep (../../../../node_modules/leaflet/dist/leaflet-src.js:4708:10)
...
(8 additional frame(s) were not displayed)
```

This seems to be similar to https://github.com/mapbox/mapbox-gl-js/issues/10402, but seemingly not the same (MapLibre doesn't have `_occlusionTimer`)

**Comment by HarelM** [comment]
From the call stack it looks like an issue with maplibre-gl-leaflet, I propose to open an issue there...

**Comment by johncarmack1984** [comment]
The stack is inside maplibre-gl-leaflet. This can be closed.
